### ISSUE TITLE
npm install error!!! error message  as below!!!RUN cd DocumentServer/sdkjs && make

### ISSUE THREAD

**Issue by xiaobing395845388** [onlyoffice-testing-robot/documentserver-from-source-build#21] opened 2019-09-10 10:56 UTC
Unexpected platform or architecture: linux/arm64
It seems there is no binary available for your platform/architecture
Try to install PhantomJS globally
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-09-10T10_50_06_053Z-debug.log

**Comment by ShockwaveNN** [comment] 2019-09-10 11:18
@xiaobing395845388 Hi, we do not support ARM yet.
Duplicate of https://github.com/ONLYOFFICE/DocumentServer/issues/152

**Closed by ShockwaveNN** 2019-09-10 11:18 UTC
